import "./dashboard.css";
import DashboardLayout from "@/components/layouts/DashboardLayout";
import { Toaster } from "sonner";
import { Providers } from "../providers"; // adjust the path as needed

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Dashboardshell({ children }) {
  return (
    <Providers>
      <DashboardLayout>
        {children}
        <Toaster position="top-right" richColors closeButton />
      </DashboardLayout>
    </Providers>
  );
}
