export const archivesData = [
  { id: 7, journal_id: 2, volume: "Vol. 1", issue: "Issue 1", published_at: "2023-01-01" },
  { id: 8, journal_id: 2, volume: "Vol. 1", issue: "Issue 2", published_at: "2023-06-01" },
  { id: 9, journal_id: 5, volume: "Vol. 2", issue: "Issue 1", published_at: "2023-07-01" },
];

export const articlesData = [
  {
    article_id: 111,
    archive_id: 7,
    title: "AI in Diagnostics",
    authors: ["Dr. A", "Dr. B"],
    volume: "Vol. 1",
    issue: "Issue 1",
    month_of_issue: "January",
    journal_status: "Published",
    year: "2023",
    doi: "10.1000/ai1",
    abstract: "This paper discusses AI use in diagnostics.",
    key_words: ["AI", "Diagnostics"],
    references: "[1] Reference A, [2] Reference B",
    page_start: "10",
    page_end: "18",
    received_date: "2022-11-01",
    revised_date: "2022-11-15",
    accepted_date: "2022-12-01",
    published_date: "2023-01-10",
    article_file: "ai-in-diagnostics.pdf",
    article_file_path: "/files/ai-in-diagnostics.pdf",
    createdAt: "2023-01-01",
  },
  {
    article_id: 1112,
    archive_id: 7,
    title: "ML in Robotics",
    authors: ["Dr. X", "Dr. Y"],
    volume: "Vol. 1",
    issue: "Issue 1",
    month_of_issue: "January",
    journal_status: "Published",
    year: "2023",
    doi: "10.1000/ml1",
    abstract: "Machine learning applications in robotics.",
    key_words: ["Machine Learning", "Robotics"],
    references: "[1] Ref ML A, [2] Ref ML B",
    page_start: "19",
    page_end: "30",
    received_date: "2022-11-10",
    revised_date: "2022-11-25",
    accepted_date: "2022-12-10",
    published_date: "2023-01-11",
    article_file: "ml-in-robotics.pdf",
    article_file_path: "/files/ml-in-robotics.pdf",
    createdAt: "2023-01-02",
  }
];